name: stylegan3
channels:
  - pytorch
  - nvidia
dependencies:
  - pyyaml
  - opencv 
  - python= 3.6
  - pip
  - numpy>=1.23.1
  - click>=8.0
  - pillow=8.3.1
  - scipy=1.7.1
  - pytorch=1.10
  - cudatoolkit=11.3
  - requests=2.26.0
  - tqdm=4.62.2
  - ninja=1.10.2
  - matplotlib
  - imageio=2.9.0
  - torchvision=0.13.1
  - pip:
    - imgui==1.3.0
    - glfw==2.2.0
    - pyopengl==3.1.5
    - imageio-ffmpeg==0.4.3
    - pyspng
    
