name: stylegan3
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  -certifi 2021.10.8
  -charset-normalizer 2.0.12
  -click 8.0.4
  -colorama 0.4.4
  -cycler 0.11.0
  -fonttools 4.31.2
  -glfw 2.5.1
  -idna 3.3
  -imageio 2.16.1
  -imageio-ffmpeg 0.4.5
  -imgui 1.4.1
  -kiwisolver 1.4.0
  -matplotlib 3.5.1
  -ninja 1.10.2.3
  -numpy 1.22.3
  -packaging 21.3
  -Pillow 9.0.1
  -pip 22.0.4
  -PyOpenGL 3.1.6
  -pyparsing 3.0.7
  -pyspng 0.1.0
  -python-dateutil 2.8.2
  -requests 2.27.1
  -scipy 1.8.0
  -setuptools 57.4.0
  -six 1.16.0
  -torch 1.11.0+cu113
  -torchaudio 0.11.0+cu113
  -torchvision 0.12.0+cu113
  -tqdm 4.63.0
  -typing_extensions 4.1.1
  -urllib3 1.26.9
