name: stylegan3-env
channels:
  -defaluts
  - pytorch
  - nvidia
dependencies:
  - pyyaml
  - opencv
  - tensorflow-gpu==2.5.0 
  - python >= 3.8
  - pip
  - numpy>=1.2.6
  - click>=8.0
  - pillow=8.3.1
  - scipy=1.7.1
  - pytorch=1.11.0
  - cudatoolkit=11.3
  - requests=2.26.0
  - tqdm=4.62.2
  - ninja=1.10.2
  - matplotlib
  - imageio=2.9.0
  - pip:
    - imgui==1.2.5
    - glfw==2.2.0
    - pyopengl==3.1.5
    - imageio-ffmpeg==0.4.3
    - pyspng
    
